#!/bin/sh

## This script will overwrite some of your home dotfiles, but it will make a backup of them in $KOKO/backup.
# TODO: add koko -y option to say "yes" to every question.
#       give warning when backup is really altering the files>

THIS="koko"
KOKO=$(realpath "$(dirname "$0")")

## FUNCTIONS

say () {
   printf "\n%s\n" "$1"
}

getAns () {
   # $1 = opt1, $2 = opt2, $3 = question, $4 = ans
   printf "\n%s [%s/%s] " "$3" "$1" "$2"
   read -r _ans
   if [ "$_ans" != "$1" ]; then
      [ "$_ans" != "$2" ] && getAns "$1" "$2" "$3" "$4"
   else
      eval "$4"="'$_ans'" ; unset _ans
   fi
}

displayHelp () {
   echo "Usage: $THIS [OPTION]"
   echo
   echo "DESCRIPTION"
   echo "Configures a friendly vim environment here \$KOKO."
   echo
   echo "OPTIONS"
   echo "-h    Print this help message."
   echo "-B    Backup files to this git directory \$KOKO."
}

mkdirBackup () {
   BACKUP="$KOKO"/backup
   [ ! -d "$BACKUP" ] && say "Creating backup directory \"$KOKO/backup\"." && mkdir -p "$BACKUP"
}

vimConfig () {
   getAns "y" "n" "Do you want to configure vim?" "_VIM"
   if [ "$_VIM" = "y" ]; then
      # backup vim stuff
      [ -f "$HOME"/.vimrc ] && cp "$HOME"/.vimrc "$BACKUP"
      [ -d "$HOME"/.vim ] && cp -r "$HOME"/.vim "$BACKUP"
      # overwrite $HOME
      cp "$KOKO"/.vimrc "$HOME"
      cp -r "$KOKO"/.vim "$HOME"/.vim
   fi
}

bashConfig () {
   getAns "y" "n" "Do you want to configure bash?" "_BASH"
   if [ "$_BASH" = "y" ]; then
      # backup bash stuff
      [ -f "$HOME"/.bashrc ] && cp "$HOME"/.bashrc "$BACKUP"
      cp "$KOKO"/.bashrc "$HOME"
      # overwrite $HOME
      [ -f "$HOME"/.inputrc ] && cp "$HOME"/.inputrc "$BACKUP"
      cp "$KOKO"/.inputrc "$HOME"
      # updating $PATH
      echo "export KOKO=$KOKO" >> "$HOME"/.bashrc
      echo "export PATH=\"\$KOKO:\$HOME/.local/bin:\$PATH\"" >> "$HOME"/.bashrc
   fi
}

gnomeConfig () {
   getAns "y" "n" "Are you in GNOME and want to configure it?" "_GNOME"
   if [ "$_GNOME" = "y" ]; then
      dconf load / < "$KOKO"/gnome/dconf.in
      [ -f "$HOME"/.config/mimeapps.list ] && cp "$HOME"/.config/mimeapps.list "$BACKUP"
      cp "$KOKO"/gnome/mimeapps.list "$HOME"/.config
      say "If you wish to store GNOME graphical configurations, run ./install.sh -B"
      echo "export TERMINAL=\"gnome-terminal\"" >> "$HOME"/.bashrc
      echo "export TERMCMD=\"gnome-terminal\"" >> "$HOME"/.bashrc
   fi
}

gnomeBackup () {
   getAns "y" "n" "Do you wish to backup GNOME graphical configurations?" "_BACKUPGNOME"
   if [ "$_BACKUPGNOME" = "y" ]; then
      dconf dump / > "$KOKO"/gnome/dconf.in
      [ -f "$HOME"/.config/mimeapps.list ] && cp "$HOME"/.config/mimeapps.list "$KOKO"/gnome/mimeapps.list
   fi
}


keyboard () {
   getAns "y" "n" "Do you want to configure the keyboard?" "_KEYBOARD"
   if [ "$_KEYBOARD" = "y" ]; then
      xset r rate 250 60
      setxkbmap -option "caps:swapescape"
   fi
}

config () {
   # you will not run this as root
   [ "$(id -u)" = 0 ] && echo "Run this installation script as a normal user." && exit 0
   # welcome
   say "This script will overwrite some of your dotfiles, but it will backup them at \"$KOKO/backup.\""
   getAns "y" "n" "Do you wish to continue?" "_CONTINUE"
   [ "$_CONTINUE" != "y" ] && say "Nothing done." && exit 0
   mkdirBackup
   vimConfig
   bashConfig
   gnomeConfig
   keyboard
   say "Installation finished." ; echo
}

backup () {
   getAns "y" "n" "Do you wish to backup ~/.vimrc and ~/.vim files?" "_BACKUPVIM"
   [ "$_BACKUPVIM" = "y" ] && cp -r "$HOME"/.vim "$HOME"/.vimrc "$KOKO"
   getAns "y" "n" "Do you wish to backup ~/.bashrc and ~/.inputrc?" "_BACKUPBASH"
   [ "$_BACKUPBASH" = "y" ] && cp -r "$HOME"/.bashrc "$HOME"/.inputrc "$KOKO"
   gnomeBackup
   say "Backup complete." ; echo
}


##############################


while getopts ":hB" option; do
   case $option in
      h)
         displayHelp
         exit 0;;
      B)
         backup
         exit 0;;
      \?) # invalid option
         echo "$THIS: invalid option." >&2
         exit 1;;
   esac
done

if [ "$OPTIND" = 1 ]; then
   config && exit 0
fi
