#!/bin/sh

# TODO: give warning when backup is really altering the files.

THIS="koko"
KOKO=$(realpath "$(dirname "$0")")
. "$KOKO"/koko_variables

## FUNCTIONS

say () {
   printf "\n%s\n" "$1"
}

getAns () {
   # $1 = opt1, $2 = opt2, $3 = question, $4 = ans
   printf "\n%s [%s/%s] " "$3" "$1" "$2"
   read -r _ans
   if [ "$_ans" != "$1" ]; then
      [ "$_ans" != "$2" ] && getAns "$1" "$2" "$3" "$4"
   else
      eval "$4"="'$_ans'" ; unset _ans
   fi
}

displayHelp () {
   echo "Usage: $THIS [OPTION]"
   echo
   echo "DESCRIPTION"
   echo "Configures a friendly vim environment here \$KOKO."
   echo
   echo "OPTIONS"
   echo "-h    Print this help message."
   echo "-y    Run as default, but say yes to every question."
   echo "-b    Backup files to this directory \$KOKO."
   echo "-B    Backup as \"-b\", but say yes to every question."
}

mkdirBackup () {
   BACKUP="$KOKO"/backup
   [ ! -d "$BACKUP" ] && say "Creating backup directory \"$KOKO/backup\"." && mkdir -p "$BACKUP"
}

vimConfig () {
   if [ -z "$1" ]; then
      getAns "y" "n" "Do you want to configure vim?" "_VIM"
   else
      _VIM="$1"
   fi
   if [ "$_VIM" = "y" ]; then
      # backup vim stuff
      [ -f "$HOME"/.vimrc ] && cp "$HOME"/.vimrc "$BACKUP"
      [ -d "$HOME"/.vim ] && cp -r "$HOME"/.vim "$BACKUP"
      # overwrite $HOME
      cp "$KOKO"/.vimrc "$HOME"
      cp -r "$KOKO"/.vim "$HOME"/.vim
   fi
}

bashConfig () {
   if [ -z "$1" ]; then
      getAns "y" "n" "Do you want to configure bash?" "_BASH"
   else
      _BASH="$1"
   fi
   if [ "$_BASH" = "y" ]; then
      # backup bash stuff
      [ -f "$HOME"/.bashrc ] && cp "$HOME"/.bashrc "$BACKUP"
      cp "$KOKO"/.bashrc "$HOME"
      # overwrite $HOME
      [ -f "$HOME"/.inputrc ] && cp "$HOME"/.inputrc "$BACKUP"
      cp "$KOKO"/.inputrc "$HOME"
      # updating $PATH
      { echo "export KOKO=$KOKO";
        echo "export PATH=\"\$HOME/.local/bin:\$PATH\"";
        echo "export PYTHONPATH=\"\$HOME/.local/lib/py-modules\""; } >> "$HOME"/.bashrc
   fi
}

gnomeConfig () {
   if [ -z "$1" ]; then
      getAns "y" "n" "Are you in GNOME and want to configure it?" "_GNOME"
   else
      _GNOME="$1"
   fi
   if [ "$_GNOME" = "y" ]; then
      [ ! -d "$HOME"/.config ] && mkdir -p "$HOME"/.config
      WALLPAPER="$(basename "$(find "$KOKO"/gnome -name "wallpaper.*" | sed 1q)")"
      cp "$KOKO"/gnome/"$WALLPAPER" "$HOME"/.config
      sed "s|HOMEPLACEHOLDER|${HOME}|;
           s|WALLPAPERPLACEHOLDER|${HOME}/.config/${WALLPAPER}|" "$KOKO"/gnome/dconf.in | dconf load /
      [ -f "$HOME"/.config/mimeapps.list ] && cp "$HOME"/.config/mimeapps.list "$BACKUP"
      cp "$KOKO"/gnome/mimeapps.list "$HOME"/.config
      say "If you wish to store GNOME configurations, run ./koko -b"
      echo "export TERMINAL=\"gnome-terminal\"" >> "$HOME"/.bashrc
      echo "export TERMCMD=\"gnome-terminal\"" >> "$HOME"/.bashrc
   fi
}

gnomeBackup () {
   if [ -z "$1" ]; then
      getAns "y" "n" "Do you wish to backup GNOME graphical configurations?" "_BACKUPGNOME"
   else
      _BACKUPGNOME="$1"
   fi
   if [ "$_BACKUPGNOME" = "y" ]; then
      dconf dump / > "$KOKO"/gnome/dconf.in
      [ -f "$HOME"/.config/mimeapps.list ] && cp "$HOME"/.config/mimeapps.list "$KOKO"/gnome/mimeapps.list
   fi
}


keyboard () {
   if [ -z "$1" ]; then
      getAns "y" "n" "Do you want to configure the keyboard?" "_KEYBOARD"
   else
      _KEYBOARD="$1"
   fi
   if [ "$_KEYBOARD" = "y" ]; then
      xset r rate 250 60
      setxkbmap -option "caps:swapescape"
   fi
}

configPython () {
   if [ -z "$1" ]; then
      getAns "y" "n" "Do you want to install python3-pip?" "_PIP"
   else
      _PIP="$1"
   fi
   [ "$_PIP" != "y" ] && echo "We did not install pip or any python libraries." && exit 0
   "$KOKO"/python/pylibs.sh
}

configBinaries () {
   [ ! -d "$HOME"/.local/bin ] && mkdir -p "$HOME"/.local/bin
   echo "Copying my scripts/binaries to \$HOME/.local/bin..."
   cp -r "$KOKO"/bin/. "$HOME/.local/bin"
   if [ -z "$1" ]; then
      getAns "y" "n" "Do you want to get some dev binaries?" "_BINARIES"
   else
      _BINARIES="$1"
   fi
   if [ "$_BINARIES" = "y" ]; then
      mkdir -p "$KOKO"/root && cd "$KOKO"/root || exit 1
      apt-get download xclip && dpkg -x xclip*.deb "$KOKO"/root
      apt-get download git && dpkg -x git*.deb "$KOKO"/root
      cp -r "$KOKO"/root/usr/. "$HOME"/.local   # copying all software files to ~/.local
      # configuring git
      [ -z "$MYNAME" ] && MYNAME="Mateus Marques"
      [ -z "$MYEMAIL" ] && MYEMAIL="mateusmarques2001@usp.br"
      { echo "[user]";
        echo "    name = $MYNAME";
        echo "    email = $MYEMAIL";
        echo "[core]";
        echo "    editor = vim";
        echo "[init]";
        echo "    templatedir = $HOME/.local/share/git-core/templates"; } > "$HOME"/.gitconfig
   fi
}

config () {
   # you will not run this as root
   [ "$(id -u)" = 0 ] && echo "Run this installation script as a normal user." && exit 0
   # welcome
   say "This script will overwrite some of your dotfiles, but it will backup them at \"$KOKO/backup\"."
   getAns "y" "n" "Do you wish to continue?" "_CONTINUE"
   [ "$_CONTINUE" != "y" ] && say "Nothing done." && exit 0
   mkdirBackup
   vimConfig
   bashConfig
   gnomeConfig
   keyboard
   configBinaries
   configPython
   say "Configuration finished." ; echo
}

# the same as "config", but say "yes" to every question
configYes () {
   # you will not run this as root
   [ "$(id -u)" = 0 ] && echo "Run this installation script as a normal user." && exit 0
   # welcome
   say "This script will overwrite some of your dotfiles, but it will backup them at \"$KOKO/backup\"."
   say "Since you included the \"-y\" option, we say \"yes\" to every question."
   _CONTINUE="y"
   [ "$_CONTINUE" != "y" ] && say "Nothing done." && exit 0
   mkdirBackup
   echo "Making backup..."
   vimConfig "y"
   echo "Configuring vim..."
   bashConfig "y"
   echo "Configuring bash..."
   gnomeConfig "y"
   echo "Configuring GNOME..."
   keyboard "y"
   echo "Configuring keyboard..."
   configBinaries "y"
   echo "Configuring binaries..."
   configPython "y"
   echo "Configuring python..."
   say "Installation finished." ; echo
}

backup () {
   getAns "y" "n" "Do you wish to backup ~/.vimrc and ~/.vim files?" "_BACKUPVIM"
   [ "$_BACKUPVIM" = "y" ] && cp -r "$HOME"/.vim "$HOME"/.vimrc "$KOKO"
   getAns "y" "n" "Do you wish to backup ~/.bashrc and ~/.inputrc?" "_BACKUPBASH"
   [ "$_BACKUPBASH" = "y" ] && cp -r "$HOME"/.bashrc "$HOME"/.inputrc "$KOKO"
   gnomeBackup
   say "Backup complete." ; echo
}

# same as "backup", but say "yes" to every question
backupYes () {
   _BACKUPVIM="y" && echo "Making backup of vim files..."
   [ "$_BACKUPVIM" = "y" ] && cp -r "$HOME"/.vim "$HOME"/.vimrc "$KOKO"
   _BACKUPBASH="y" && echo "Making backup of bash files..."
   [ "$_BACKUPBASH" = "y" ] && cp -r "$HOME"/.bashrc "$HOME"/.inputrc "$KOKO"
   gnomeBackup "y"
   say "Backup complete." ; echo
}


##############################


while getopts ":hybB" option; do
   case $option in
      h)
         displayHelp && exit 0
         exit 1;;
      y)
         configYes && exit 0
         exit 1;;
      b)
         backup && exit 0
         exit 1;;
      B)
         backupYes && exit 0
         exit 1;;
      \?) # invalid option
         echo "$THIS: invalid option." >&2
         exit 1;;
   esac
done

if [ "$OPTIND" = 1 ]; then
   config && exit 0
   exit 1
fi
